### ISSUE TITLE
No Gifted options appear

### ISSUE THREAD

**Issue by sportivod** [mkdo/woocommerce-gift-aid#5]
Hi, I have followed your instructions and the plugin is activated, but it doesn't seem to do anything. There are no settings in the product tab and nothing at checkout either. I'm using WP 4.3.1 and WC 2.4.11.

Thanks for any help!
Dominic

**Comment by sportivod** [comment]
WP just did an auto-update and now it seems to be working fine. Thanks very much for any time!
Best,
Dominic

**Comment by davetgreen** [comment]
hey @sportivod thanks for posting the ticket anyway. I'll try and recreate with those specific versions when I have some time this weekend. Glad it's resolved!

hope you're finding the plugin useful. I've submitted it to the WordPress.org plugin repository under a slightly different name (Gift Aid for WooCommerce now) so once it's accepted you'll be able to install that version and update it via the usual way. :)
